version: '3.8'

services:
  web:
    image: centroquirurgicosistema
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: centroQuirurgico

      ports:
        "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: