version: '3.8'

services:
  web:
    image: centroquirurgicosistema
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: centroquirurgico
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: